base_url: https://jsonplaceholder.typicode.com
headers:
  User-Agent: "APITestFramework/1.0"
  Accept: "application/json"
endpoints:
  - path: /posts
    method: GET
    response_schema:
      type: array
      items:
        type: object
        properties:
          userId:
            type: integer
          id:
            type: integer
          title:
            type: string
          body:
            type: string
  - path: /posts
    method: POST
    response_schema:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        userId:
          type: integer

test_data:
  - data: null
    expected_status: 200
  - data:
      title: "foo"
      body: "bar"
      userId: 1
    expected_status: 201
    headers:
      Content-Type: "application/json"
  - params:
      userId: 1
    expected_status: 200
