base_url: https://api.example.com
headers:
  User-Agent: "APITestFramework/1.0"
  Accept: "application/json"
auth:
  username: "your_username"
  password: "your_password"
endpoints:
  - path: /users
    method: GET
    response_schema:
      type: array
      items:
        type: object
        properties:
          id: 
            type: integer
          name: 
            type: string
  - path: /users
    method: POST
    response_schema:
      type: object
      properties:
        id: 
          type: integer
        name: 
          type: string

test_data:
  - data: null
    expected_status: 200
  - data:
      name: "John Doe"
    expected_status: 201
    headers:
      Content-Type: "application/json"
  - params:
      page: 1
      per_page: 10
    expected_status: 200